name: Build Selaura Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sdk.lib manually
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" >nul
          cd sdk
          lib /nologo /def:sdk.def /out:..\build\sdk.lib /machine:x64


      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build DLL
        run: cmake --build build --config Release --verbose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selaura-build
          path: |
            build/**/*.dll
            build/**/*.lib
            build/**/*.pdb
